#!/usr/bin/env bash

# SketchyBar configuration

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar height=38 \
                 y_offset=0 \
                 position=top \
                 padding_left=0 \
                 padding_right=0 \
                 margin=0 \
                 color=0xff000000 \
                 shadow=on \
                 sticky=on

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
# Workspace indicator
sketchybar --add item workspace left \
    --set workspace \
    icon= \
    icon.color=0xff89b4fa \
    background.color=0xff313244 \
    background.corner_radius=5 \
    background.height=24 \
    background.padding_left=8 \
    background.padding_right=8 \
    padding_left=10 \
    padding_right=5 \
    script="$PLUGIN_DIR/workspace.sh" \
    --subscribe workspace aerospace_workspace_change

# Front app
sketchybar --add item front_app left \
    --subscribe front_app front_app_switched \
    --set front_app \
    background.color=0xff45475a \
    background.corner_radius=5 \
    background.height=20 \
    script="$PLUGIN_DIR/front_app.sh"

##### Right Items #####
# Clock
sketchybar --add item clock right \
    --set clock \
    icon= \
    script="$PLUGIN_DIR/clock.sh" \
    update_freq=10

# Weather
sketchybar --add item weather right \
           --set weather update_freq=600 \
                        icon= \
                        icon.font="Hack Nerd Font:Bold:14.0" \
                        label.font="Hack Nerd Font:Bold:12.0" \
                        icon.color=0xff5edaff \
                        script="$PLUGIN_DIR/weather.sh" \
           --subscribe weather system_woke

# Slack
sketchybar --add item slack right \
           --set slack \
                 update_freq=180 \
                 script="$PLUGIN_DIR/slack.sh" \
                 icon.font.size=20 \
                 click_script="open -a 'Slack'" \
           --subscribe slack system_woke

# Telegram
sketchybar --add item telegram right \
           --set telegram \
                 update_freq=180 \
                 script="$PLUGIN_DIR/telegram.sh" \
                 icon.font.size=20 \
                 click_script="open -a 'Telegram'" \
           --subscribe telegram system_woke

# Battery
sketchybar --add item battery right \
    --subscribe battery system_woke power_source_change \
    --set battery \
    script="$PLUGIN_DIR/battery.sh"

# Volume
sketchybar --add item volume right \
    --subscribe volume volume_change \
    --set volume \
    script="$PLUGIN_DIR/volume.sh"

##### Finalizing Setup #####
sketchybar --update