#!/usr/bin/env bash

# SketchyBar configuration

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar height=38 \
                 y_offset=0 \
                 position=top \
                 padding_left=0 \
                 padding_right=0 \
                 margin=0 \
                 color=0xff1e1e2e \
                 shadow=on \
                 sticky=on

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
# AeroSpace workspace indicator
sketchybar --add event aerospace_workspace_change
sketchybar --add item current_workspace left \
    --subscribe current_workspace aerospace_workspace_change \
    --set current_workspace \
    background.color=0xff313244 \
    background.corner_radius=5 \
    background.height=20 \
    label="" \
    script="$PLUGIN_DIR/aerospace.sh"

# Front app
sketchybar --add item front_app left \
    --subscribe front_app front_app_switched \
    --set front_app \
    background.color=0xff45475a \
    background.corner_radius=5 \
    background.height=20 \
    script="$PLUGIN_DIR/front_app.sh"

##### Right Items #####
# Clock
sketchybar --add item clock right \
    --set clock \
    icon= \
    script="$PLUGIN_DIR/clock.sh" \
    update_freq=10

# Battery
sketchybar --add item battery right \
    --subscribe battery system_woke power_source_change \
    --set battery \
    script="$PLUGIN_DIR/battery.sh"

# Volume
sketchybar --add item volume right \
    --subscribe volume volume_change \
    --set volume \
    script="$PLUGIN_DIR/volume.sh"

# WiFi
sketchybar --add item wifi right \
    --subscribe wifi wifi_change \
    --set wifi \
    script="$PLUGIN_DIR/wifi.sh"

##### Finalizing Setup #####
sketchybar --update