code --install-extension akamud.vscode-theme-onelight
code --install-extension anoff.theme-monokai-light
code --install-extension armandphilippot.coldark
code --install-extension be5invis.toml
code --install-extension brapifra.phpserver
code --install-extension davidanson.vscode-markdownlint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension hookyqr.beautify
code --install-extension johnpapa.vscode-peacock
code --install-extension lonefy.vscode-js-css-html-formatter
code --install-extension mathcale.theme-dracula-refined
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mohd-akram.vscode-html-format
code --install-extension moyu.snapcode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension sabrsorensen.synthwave-blues
code --install-extension skyapps.fish-vscode
code --install-extension svipas.light-plus-pro
code --install-extension tomoki1207.pdf
code --install-extension tonsky.theme-alabaster
code --install-extension trungngo.autoflake
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vue.volar
code --install-extension yinfei.luahelper
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhang-renyang.chat-gpt
code --install-extension zxh404.vscode-proto3